x-api-env: &api-env
  PORT: "9999"
  USE_MMAP: "true"
  NPROBE: "8"
  INDEX_PATH: "/resources/index.bin"

x-api: &api
  build:
    context: .
    dockerfile: Dockerfile
  image: backend-war-go-api:local
  platform: linux/amd64
  cpus: "0.4"
  mem_limit: "152m"
  volumes:
    - sockets:/sockets
    - ./resources:/resources:ro
  networks:
    - rinha-net
  logging:
    driver: "none"
  ulimits:
    nofile:
      soft: 65535
      hard: 65535

services:
  lb:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    container_name: rinha-lb
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    cpus: "0.2"
    mem_limit: "46m"
    networks:
      - rinha-net
    logging:
      driver: "none"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    <<: *api
    container_name: rinha-api-1
    environment:
      <<: *api-env
      UDS_PATH: /sockets/api1.sock
      UDS_MODE: "438"

  api2:
    <<: *api
    container_name: rinha-api-2
    environment:
      <<: *api-env
      UDS_PATH: /sockets/api2.sock
      UDS_MODE: "438"

networks:
  rinha-net:
    driver: bridge

volumes:
  sockets:
