x-api-env: &api-env
  PORT: "9999"
  SEARCH_ENGINE: "knn_tree"
  #SEARCH_ENGINE: "ivf"
  NPROBE: "8"
  INDEX_PATH_IVF: "/resources/index_ivf.bin"
  INDEX_PATH_KNN: "/resources/index_knn.bin"

x-api: &api
  image: ghcr.io/nicolasmmb/backend-war-go:latest
  platform: linux/amd64
  cpus: "0.4"
  mem_limit: "152m"
  volumes:
    - sockets:/sockets
  networks:
    - rinha-net
  ulimits:
    nofile:
      soft: 65535
      hard: 65535

services:
  lb:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    container_name: rinha-lb
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    cpus: "0.2"
    mem_limit: "46m"
    networks:
      - rinha-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    <<: *api
    container_name: rinha-api-1
    environment:
      <<: *api-env
      UDS_PATH: /sockets/api1.sock
      UDS_MODE: "438"

  api2:
    <<: *api
    container_name: rinha-api-2
    environment:
      <<: *api-env
      UDS_PATH: /sockets/api2.sock
      UDS_MODE: "438"

networks:
  rinha-net:
    driver: bridge

volumes:
  sockets:
